---
- name: Install Software | Carbon Black
  hosts: all
  gather_facts: yes

  # vars:
  #   cb_package: "cbsensor"

  # roles:
  #  - ans_carbonblack_installclient_role

  tasks:
    # - name: check if package is installed
    #   package:
    #     name: "{{ cb_package }}"
    #     state: present
    #     check_mode: true
    #   register: package_check

    # - name: print stuff
    #   debug:
    #     msg:  "{{ package_check }}"

    - name: Import role for carbon black install
      ansible.builtin.import_role:
        name: ans_carbonblack_bootstrap_role
