---
# Added role for linux tasks
 - src: git+https://git.temple.edu/engineering-operations/server-administration/ans_linux_misc_role.git
   scm: git

# Added for install_carbonblack
 - src: git+https://git.temple.edu/its-infosec/vmware-carbon-black/ans_carbonblack_bootstrap_role.git
   scm: git
