---
- name: Remove sudoers file
  hosts: all # should force host to be specified instead of all keyword so mistake isnt made
  gather_facts: true

  tasks:
    - name: Include role to remove sudoers file
      ansible.builtin.include_role:
        name: ans_sysadmin_linux_role
        tasks_from: "sudoers/sudoers_remove.yml"
      vars:
        which_group: ""
