---
- name: Remove sudoers file
  hosts: all #should force host to be specified instead of all keyword so mistake isnt made
  gather_facts: no

  tasks:
    - name: Include role to remove sudoers file
      ansible.builtin.include_role:
        name: ans_linux_sudoers_role
        tasks_from: sudoers_remove.yml
      vars:
          which_group: ""


