---
- name: Create service account
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Create user
      ansible.builtin.include_role:
        name: ans_linux_misc_role
        tasks_from: "users/create_svcaccts.yml"
      vars:
        account: "{{ account_name }}"